### ISSUE TITLE
Prometheus server shut down - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mmianl** [supabase/gotrue#1136]
When setting the env vars `GOTRUE_METRICS_ENABLED` to `true` and `GOTRUE_METRICS_EXPORTER` to `prometheus`, gotrue crashes right after starting with the following log output:
```json
{"level":"info","msg":"Go runtime metrics collection started","time":"2023-06-14T07:09:16Z"}
{"level":"info","msg":"prometheus server listening on 0.0.0.0:9100","time":"2023-06-14T07:09:16Z"}
{"level":"info","msg":"received graceful shutdown signal","time":"2023-06-14T07:09:16Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5f85b4]

goroutine 1 [running]:
net/url.(*URL).Query(0xc00004a017?)
	/usr/local/go/src/net/url/url.go:1118 +0x14
github.com/supabase/gotrue/cmd.migrate(0x0?, {0x0?, 0x0?, 0x0?})
	/go/src/github.com/supabase/gotrue/cmd/migrate_cmd.go:55 +0x23c
github.com/supabase/gotrue/cmd.glob..func3(0x19a9060, {0x19fb890?, 0x0?, 0x0?})
	/go/src/github.com/supabase/gotrue/cmd/root_cmd.go:17 +0x25
github.com/spf13/cobra.(*Command).execute(0x19a9060, {0xc00003e230, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x19a9060)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(0x1283a38?, {0x12848e0?, 0xc00009d8c0?})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961 +0x4a
main.main()
	/go/src/github.com/supabase/gotrue/main.go:31 +0x10c
```

I'm running gotrue in an AKS environment with the following deployment manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotrue
    app.kubernetes.io/instance: gotrue
    app.kubernetes.io/name: gotrue
    app.kubernetes.io/version: v2.72.0
    version: v2.72.0
  name: gotrue
  namespace: gotrue
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: gotrue
      app.kubernetes.io/name: gotrue
      app.kubernetes.io/version: v2.72.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gotrue
        app.kubernetes.io/instance: gotrue
        app.kubernetes.io/name: gotrue
        app.kubernetes.io/version: v2.72.0
        version: v2.72.0
    spec:
      containers:
      - env:
        - name: GOTRUE_SITE_URL
          value: example.com
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: gotrue-jwt
        - name: LOG_LEVEL
          value: debug
        - name: DB_HOST
          value: example.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: gotrue-psql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: gotrue-psql
        - name: GOTRUE_DB_DATABASE_URL
          value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
        - name: GOTRUE_DB_DRIVER
          value: postgres
        - name: GOTRUE_METRICS_ENABLED
          value: "true"
        - name: GOTRUE_METRICS_EXPORTER
          value: prometheus
        image: supabase/gotrue:v2.72.0
        imagePullPolicy: IfNotPresent
        name: gotrue
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        - containerPort: 9100
          name: http-metrics
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER); do
          echo "Waiting for database to start..."
          sleep 2
          done
        - echo "Database is ready"
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_HOST
          value: example.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: gotrue-psql
        image: postgres:14-alpine
        imagePullPolicy: IfNotPresent
        name: init-db
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      serviceAccount: gotrue
      serviceAccountName: gotrue
      terminationGracePeriodSeconds: 30
```
