### ISSUE TITLE
Latest Release of `supabase/gotrue` returns a `null` session on `/token?grant_type=refresh_token`

### ISSUE THREAD

**Issue by acupofjose** [supabase/gotrue#348]
# Bug report

## Describe the bug

When POSTing to the `/token?grant_type=refresh_token` endpoint it now returns `null` instead of a session.

## To Reproduce

Using the following `docker-compose.yml`:

```yml
version: "3"
services:

  gotrue:
    image: supabase/gotrue:latest
    ports:
      - "9999:9999"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      GOTRUE_JWT_SECRET: "37c304f8-51aa-419a-a1af-06154e63707a"
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      API_EXTERNAL_URL: http://localhost
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9999
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_SITE_URL: http://localhost
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      GOTRUE_EXTERNAL_PHONE_ENABLED: 'true'
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMS_AUTOCONFIRM: 'true'
      GOTRUE_SMS_PROVIDER: "twilio"

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./GotrueTests/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
```

Running:

```bash
curl --location --request POST 'http://localhost:9999/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "testing@supabase.io",
    "password": "super-secure-password"
}'
```

Produces:
```json
{
    "token_type": "bearer",
    "expires_in": 3600,
    "refresh_token": "08OhZcnl0ep_i1HbUVMyMQ",
   // ....
}
```

Then taking the `refresh_token` from above:

```bash
curl --location --request POST 'http://localhost:9999/token?grant_type=refresh_token' \
--header 'Content-Type: application/json' \
--data-raw '{
    "refresh_token": "08OhZcnl0ep_i1HbUVMyMQ"
}'
```

Produces:
```json
null
```

## Expected behavior

Endpoint should return a session

## System information

- Gotrue 2.3.7 (latest)
- OS: Docker

## Additional context

Ref: supabase-community/gotrue-csharp#25
