### ISSUE TITLE
Support docker file-based secrets natively

### ISSUE THREAD

**Issue by sweatybridge** [supabase/gotrue#898]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be great if gotrue supported [Docker Secrets](https://docs.docker.com/engine/swarm/secrets), and `*_FILE` versions of the variables that hold secrets, so that we can pass a secrets file vs. the raw value:

```yaml
services:
  gotrue:
    image: supabase/gotrue:v2.40.1
    restart: unless-stopped
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret
```

The current `GOTRUE_JWT_SECRET` variable could still be supported alongside `GOTRUE_JWT_SECRET_FILE`, and the same for all other secrets. This would let current code continue to work, but migrate to a more secure method of injecting secrets.

## Describe alternatives you've considered

entrypoint approach was rejected https://github.com/supabase/gotrue/pull/642

## Additional context

upstream issue https://github.com/supabase/supabase/issues/6014
