### ISSUE TITLE
Can't change default email templates

### ISSUE THREAD

**Issue by Luca8991** [supabase/gotrue#899]
# Bug report

## Describe the bug

Setting email templates from environment variables doesn't work in [self-hosted Docker Supabase](https://github.com/supabase/supabase/tree/master/docker)
In [self-hosted Docker Supabase](https://github.com/supabase/supabase/tree/master/docker), after setting `GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE` I'm still receiving the email with the [default template](https://github.com/supabase/gotrue/blob/master/mailer/template.go#L50-L54).

## To Reproduce

1. use [docker-comopse.yml](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) to launch a self-hosted Supabase project
2. set `GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE` to (as per [docs](https://supabase.com/docs/reference/tools/reference-auth#email-templates)):
    ```
    GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE: "<h2>Confirm your Email</h2><p>Changing from {{ .Email }} to {{ .NewEmail }}:</p><p><a href='{{ .ConfirmationURL }}'>Change Email</a></p><p>Alternatively, enter the code: {{ .Token }}</p><p>Thanks</p>"
    ```
4. change email using [update()](https://supabase.com/docs/reference/javascript/auth-update) from Nodejs client (after authenticating user with current email)
5. still receive change email confirmation with [default template](https://github.com/supabase/gotrue/blob/master/mailer/template.go#L50-L54):
    ```
    Confirm email address change
    Follow this link to confirm the update of your email address from [mycurrentemail@example.com](mailto:mycurrentemail@example.com) to [mynewemail@example.com](mailto:mynewemail@example.com):

    [Change email address link] (I won't paste it here)

    Alternatively, enter the code: <email-change-token>
    ```

**N.B.:** setting [custom subjects](https://supabase.com/docs/reference/tools/reference-auth#email) from environment variables works as expected. 

## Expected behavior

Receive the email change confirmation with the custom template set from environment variables.

## System information

- OS: Ubuntu 20.04 LTS
- Docker: Docker version 22.06.0-beta.0, build 3e9117b
- docker-compose: Docker Compose version v2.6.1
- supabase/gotrue: v2.5.21 (Docker image)
- Version of supabase-js: 1.35.4
- Version of Node.js: v16.14.1

**Comment by sweatybridge** [comment]
The mailer config has be renamed in gotrue 2.40.1 to be clearer that it is expecting a url path.
```yaml
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE}
```

**Comment by Benjythebee** [comment]
Still struggling in changing the templates to this day as there is very little documentation on it;

I also note the env variables `GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE` exist but when I look them up in the codebase, they seem unused. is that normal?

**Comment by silentworks** [comment]
@Benjythebee they are used in the codebase of Gotrue. You won't find reference to these variables directly as they are handled by the [envconfig](https://github.com/kelseyhightower/envconfig) library. But you can see the struct with the `email_change` part of its name here https://github.com/supabase/gotrue/blob/4ff1fe058cfab418c445808004091e89dcf87124/internal/conf/configuration.go#L159, you can also see where [envconfig](https://github.com/kelseyhightower/envconfig) starts parsing the environment variable here https://github.com/supabase/gotrue/blob/4ff1fe058cfab418c445808004091e89dcf87124/internal/conf/configuration.go#L347.

Are you trying to change the templates in self-hosted or in the CLI setup? if self-hosted once you make the change you need to restart your docker containers for the change to take effect.

**Comment by Benjythebee** [comment]
That makes a lot of sense, thanks a lot! Self-hosted, I think it was just a matter of understanding what to change and to what

**Comment by DavidCks** [comment]
I got it to work. Here's what I did:

docker-compose.yml
```yml
services:
  auth:
    environment:
      # Map mailer template url stored in .env to the GOTRUE env var
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: ${MAILER_TEMPLATES_CONFIRMATION}

  # Add nginx to serve static html
  nginx:
    container_name: supabase-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80" # Expose port 8080 for your static files
    volumes:
      - ./local/path/to/template/folder:/usr/share/nginx/html:ro # Map your external static folder to the container
    networks:
      - supabase_default # Ensure this matches your existing network setup
      # you can check the networks with `docker network ls` 
      # and see whats running within a network with `docker network inspect {network-name}`

networks:
  supabase_default: # Ensure this matches your existing network setup
    external: true
```

.env
```ini
MAILER_TEMPLATES_CONFIRMATION=http://nginx:80/confirm.html
```

and for completions sake:
./local/path/to/template/folder/confirm.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Sign Up Confirmation</title>
  </head>
  <body>
    <h1>Sign Up Confirmation</h1>
    <p>Thank you for signing up!</p>
    <p>Please copy the code below into the App to confirm your email</p>
    <p>{{ .Token }}</p>
  </body>
</html>
```
